version: "3.8"
services:
  web:
    build: .
    container_name: icmobi-website
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mern_db
    volumes:
      - ./backend:/icmobi-website/backend
      - /icmobi-website/backend/node_modules

  mongo:
    image: mongo:6
    container_name: mern_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
